Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
